name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'website/docs/**/*.md'
      - 'website/docusaurus.config.js'
      - 'website/sidebars.js'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            website/pnpm-lock.yaml
      - name: Install Root dependencies
        run: pnpm i
      - name: Install Website dependencies
        working-directory: ./website
        run: pnpm i
      - name: Set git user email and name
        run: |
          git config --global user.email "qq1324318532@gmail.com"
          git config --global user.name "icebreaker-bot"
      - name: Build website and Deploy to GitHub Pages
        working-directory: ./website
        # Error: Please set the GIT_USER environment variable, or explicitly specify USE_SSH instead!
        run: GIT_USER=sonofmagic pnpm run deploy:github
