name: test

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # https://github.com/webpack/webpack/blob/main/.github/workflows/test.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 18.x]
        part: [a, b]
        include:
          - os: ubuntu-latest
            node-version: 18.x
            part: a
          - os: ubuntu-latest
            node-version: 16.x
            part: a
          - os: ubuntu-latest
            node-version: 14.x
            part: a
          - os: ubuntu-latest
            node-version: 12.x
            part: a
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ^7.27.1
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - run: pnpm i
      - run: pnpm build
      - run: pnpm test

      - uses: codecov/codecov-action@v3
        with:
          directory: coverage
