name: test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    # https://github.com/webpack/webpack/blob/main/.github/workflows/test.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x, 16.x, 18.x, 20.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm i
      - run: pnpm postinstall
      - run: pnpm build
      - run: pnpm test

      - uses: codecov/codecov-action@v3
        with:
          directory: coverage
          # files: ./coverage/clover.xml,./coverage-vitest/clover.xml
